export const PROJECT_PREVIEW = [
  "sh -c '",
  'path="$1";',
  'if [ -f "$path/README.md" ]; then',
  "  if command -v bat >/dev/null 2>&1; then",
  '    bat --color=always -- "$path/README.md";',
  "  else",
  '    head -50 "$path/README.md";',
  "  fi;",
  'elif [ -d "$path" ]; then',
  '  command ls -la -- "$path" 2>/dev/null | head -50;',
  "else",
  '  printf "%s\\n" "$path";',
  "fi",
  "' sh {}",
].join(" ");

export const WORKSPACE_PREVIEW = [
  "sh -c '",
  'label="$1";',
  'summary="$2";',
  'cwd="$3";',
  'branch="$4";',
  'tabs="$5";',
  'panes="$6";',
  'printf \"label: %s\\n\" \"$label\";',
  'printf \"summary: %s\\n\" \"$summary\";',
  'if [ -n \"$branch\" ]; then printf \"branch: %s\\n\" \"$branch\"; fi;',
  'if [ -n \"$cwd\" ]; then printf \"cwd: %s\\n\" \"$cwd\"; fi;',
  'printf \"tabs: %s\\npanes: %s\\n\\n\" \"$tabs\" \"$panes\";',
  'if [ -n \"$cwd\" ] && [ -f \"$cwd/README.md\" ]; then',
  "  if command -v bat >/dev/null 2>&1; then",
  '    bat --color=always -- \"$cwd/README.md\";',
  "  else",
  '    head -50 \"$cwd/README.md\";',
  "  fi;",
  'elif [ -n \"$cwd\" ] && [ -d \"$cwd\" ]; then',
  '  command ls -la -- \"$cwd\" 2>/dev/null | head -50;',
  "fi",
  "' sh {2} {3} {4} {5} {6} {7}",
].join(" ");

export const WORKTREE_CANDIDATE_PREVIEW = [
  "sh -c '",
  'label="$1";',
  'detail="$2";',
  'kind="$3";',
  'branch="$4";',
  'path="$5";',
  'printf \"selection: %s\\n\" \"$label\";',
  'printf \"type: %s\\n\" \"$kind\";',
  'if [ -n \"$branch\" ]; then printf \"branch: %s\\n\" \"$branch\"; fi;',
  'if [ -n \"$detail\" ]; then printf \"%s\\n\" \"$detail\"; fi;',
  'if [ -n \"$path\" ]; then printf \"path: %s\\n\" \"$path\"; fi;',
  'printf \"\\n\";',
  'if [ -n \"$path\" ] && [ -f \"$path/README.md\" ]; then',
  "  if command -v bat >/dev/null 2>&1; then",
  '    bat --color=always -- \"$path/README.md\";',
  "  else",
  '    head -50 \"$path/README.md\";',
  "  fi;",
  'elif [ -n \"$path\" ] && [ -d \"$path\" ]; then',
  '  command ls -la -- \"$path\" 2>/dev/null | head -50;',
  "fi",
  "' sh {2} {3} {4} {5} {6}",
].join(" ");
